online-mode=false
motd=A Mero Server
server-port=25565
properties={'level-name': 'world', 'level-type': 'minecraft:normal', 'allow-nether': 'true', 'generate-structures': 'true', 'max-build-height': '256', 'difficulty': 'peaceful', 'pvp': 'true', 'hardcore': 'false', 'allow-flight': 'false', 'spawn-protection': '16', 'max-players': '20', 'view-distance': '10', 'simulation-distance': '10', 'max-tick-time': '60000', 'online-mode': 'true', 'enforce-whitelist': 'false', 'hide-online-players': 'false', 'server-port': '25565', 'motd': ''}
meta={'display_name': '§o§k§4Amazing §8Server', 'ram': 4}
